source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Zi0P4tch0/Specs.git'
use_frameworks!
platform :ios, '8.0'

pod 'OpenCV', '2.4.9-zp'
pod 'Fabric'
pod 'TwitterKit'
pod 'SwiftyDropbox'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Typhoon'
pod 'MBProgressHUD', '~> 0.9.0'